<a href="https://colab.research.google.com/github/chaitanyaa1512/Machine-Learning/blob/main/CC_ML_SESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
dataset = pd.read_csv('/content/Data.csv')

In [15]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [16]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [25]:
X= dataset.iloc[:  ,:-1].values
y= dataset.iloc[:  ,-1].values


In [26]:
#used for more than two labels categorical data
#encoding the dependent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [28]:
#used for two label categorical data
#encoding the independent variable
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y =le.fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]


#Splitting the dataset into training and testing datasets

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2, random_state=1)
print(X_train)#80% of data input variable

[[0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [31]:
print(X_test)#20% data of input variable

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [32]:
print(y_train)#80% data of dependent variable


[0 1 0 0 1 1 0 1]


In [33]:
print(y_test)#20% data of dependent variable

[0 1]


Feature Scaling 

In [35]:
from sklearn.preprocessing import StandardScaler #method for std deviation
sc= StandardScaler()
X_train[:, 3:]=sc.fit_transform(X_train[:, 3:])
X_test[:, 3:]=sc.transform(X_test[:, 3:])
print(X_train)

[[0.0 0.0 1.0 nan -1.0182239953527132]
 [0.0 1.0 0.0 -0.03891021128204815 nan]
 [1.0 0.0 0.0 0.5058327466666259 0.5834766714942514]
 [0.0 0.0 1.0 -0.31128169025638514 -0.2974586952715791]
 [0.0 0.0 1.0 -1.8093248246152385 -1.3385641287221062]
 [1.0 0.0 0.0 1.0505757046152997 1.1440719048906889]
 [0.0 1.0 0.0 1.3229471835896367 1.4644120382600818]
 [1.0 0.0 0.0 -0.7198389087178906 -0.5377137952986237]]


In [36]:
print(X_test)


[[0.0 1.0 0.0 -1.400767606153733 -0.8580539286680166]
 [1.0 0.0 0.0 -0.44746742974355364 0.18305150478251025]]
